import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        
        <div className={styles.grid}>
          <Link href="/ssr">
            <a className={styles.card}>
              <h2>SSR &rarr;</h2>
              <p>Example using Server Side Rendering</p>
            </a>
          </Link>

          <Link href="/ssg">
            <a className={styles.card}>
              <h2>SSG &rarr;</h2>
              <p>Example using Static Site Generation</p>
            </a>
          </Link>

          <Link href="/csr">
            <a className={styles.card}>
              <h2>CSR &rarr;</h2>
              <p>Example using Client Side Rendering</p>
            </a>
          </Link>

          <Link href="/ssgWithIsr">
            <a className={styles.card}>
              <h2>SSG with ISR &rarr;</h2>
              <p>
                Example using Static Site Generation and Incremental Static Regeneration
              </p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
